Library branch working
arslanbisharat/LIBRARY pull request #1
Opened 2020-07-01 16:58 UTC by arslanbisharat

### PROJECT: LIBRARY

> All the instructions are given [**Here**](https://www.theodinproject.com/courses/javascript/lessons/library) are followed in the project
>>  I completed this project alone

2020-07-02 08:48 UTC, bellom commented
> ### PROJECT: LIBRARY
> > All the instructions are given [**Here**](https://www.theodinproject.com/courses/javascript/lessons/library) are followed in the project
> > > I completed this project alone

Nice short details but you need to list the tasks you performed.
Example: 
![image](https://user-images.githubusercontent.com/31897434/70375725-88436000-1901-11ea-92e1-a8d51f615821.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/

2020-07-02 08:58 UTC, bellom requested changes
## Hi @arslanbisharat  :clap: 

#### May I know the reason why you're working alone on a collaborative project?  
#### You needs to answer this before moving on, kindly explain, thanks.

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 
 
**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-07-02 08:58 UTC, bellom commented on library.js
> +}
wow, App interface really looks nice
but Opps! just one more thing to do 👇 
Let's separate the DOM from application logic, you can create another file for DOM.

![image](https://user-images.githubusercontent.com/31897434/73420341-70e18b80-4322-11ea-840a-fa14e04b592b.png)

https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59623451/

2020-07-03 06:13 UTC, maelfosso requested changes
# Congratulations :clap: 

Thank you for applying the suggested changes.
You have a really good code now.

However, as you didn't explain why you are working alone as requested by @bellom, the last reviewer, the project can be validated.

Kindly do it please.

Mael FOSSO

2020-07-03 06:25 UTC, arslanbisharat commented
@maelfosso @bellom  This was an issue with my repair request. I have already addressed this issue to Microverse team.

2020-07-05 06:35 UTC, merged